kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "golang-sti"
spec:
  triggers:
    -
      type: "GitHub"
      github:
        secret: "secret101"
    -
      type: "Generic"
      generic:
        secret: "secret101"
    -
      type: "ImageChange"
  source:
    type: "Git"
    git:
      uri: "git://github.com/mchudgins/golang-sti.git"
    source: ""
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        namespace: "openshift"
        name: "golang:latest"

  output:
    to:
      kind: "ImageStreamTag"
      name: "golang-sti:latest"
